#!/usr/local/bin/python3
import sys
import pawnpy

print('Pawn Compiler')
if len(sys.argv) < 2:
  print('Usage: pawncc <filename>')

filename = sys.argv[1]

src = pawnpy.Source(filename)

print('Compiling %s' % filename)
src.compile()